version: '3.8'

services:
  postgresql-service:
    image: postgres:15
    container_name: postgresql-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - sonar-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 30s
      timeout: 10s
      retries: 5

  sonarqube-service:
    image: sonarqube:community
    container_name: sonarqube-container
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql-container:5432/sonarqube
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: admin123
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    networks:
      - sonar-network
    depends_on:
      postgresql-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgresql-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:

networks:
  sonar-network:
    driver: bridge
